[package]
name = "rust_kernel"
version = "0.1.0"
authors = ["kryo4096 <kryo4096@gmail.com>"]

[dependencies]
spin = "*"
bootloader_precompiled = "0.3.0"

[package.metadata.bootimage]
default-target = "x86_64-rust_kernel.json"