#!/bin/bash

bootimage build --target x86_64-rust_kernel.json

if [ $? -eq 0 ]; then
	qemu-system-x86_64 -d int -no-reboot -drive format=raw,file=bootimage.bin -m 5M
else
    echo "Compilation failed."
fi

