[package]
name = "rost_fs"
version = "0.1.0"
authors = ["kryo4096 <kryo4096@gmail.com>"]
edition = "2018"

[dependencies]
spin = "0.4"


[dependencies.rand]
default-features = false
version = "0.6"

[lib]
name = "rost_fs"
path = "src/lib.rs"

[[bin]]
name = "fscreate"
path = "src/fscreate.rs"
