[package]
name = "bootloader"
version = "0.2.0-alpha-003"
authors = ["Philipp Oppermann <dev@phil-opp.com>"]
license = "MIT/Apache-2.0"
description = "An experimental pure-Rust x86 bootloader."

[dependencies]
xmas-elf = "0.6.2"
x86_64 = { git = "https://github.com/rust-osdev/x86_64" }
usize_conversions = "0.2.0"
os_bootinfo = { git = "https://github.com/rust-osdev/os_bootinfo" }
fixedvec = "0.2.3"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = false
debug = true
