[package]
name = "bootloader"
version = "0.1.1"
authors = ["Philipp Oppermann <dev@phil-opp.com>"]
license = "MIT/Apache-2.0"
description = "An experimental pure-Rust x86 bootloader."

[dependencies]
rlibc = "1"
xmas-elf = "0.6.0"
x86_64 = "0.2.0-alpha-001"
usize_conversions = "0.2.0"
os_bootinfo = "0.2.0-alpha"
spin = "0.4.6"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
